# Generated by Django 4.1.3 on 2022-12-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demmyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demmy',
            name='date',
            field=models.DateField(default='2004-04-24'),
            preserve_default=False,
        ),
    ]
